modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/GzxingR/Translator-NeoForge/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''Non-intrusive in-game translation for chat, HUD, tooltips, signs, TextDisplay text, and more. 用于翻译聊天、界面与世界中的文字。'''
logoFile="assets/translator/icon.png"
authors="Gstar"
displayURL="https://modrinth.com/mod/translator-neoforge"

[[mixins]]
config="translator.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version_min},)"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="cloth_config"
type="required"
versionRange="[15.0.0,)"
ordering="AFTER"
side="CLIENT"
